# Generated by Django 2.2.12 on 2021-06-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0009_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
