# Generated by Django 2.2.12 on 2021-05-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('Founder', 'Founder')], max_length=50)),
                ('status', models.CharField(choices=[('Works', 'Works'), ('Dismissed', 'Dismissed'), ('On holiday', 'On holiday')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('In work', 'In work'), ('Ready to deliver', 'Ready to deliver'), ('On way', 'On way'), ('Delivered', 'Deliverd')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_server.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_server.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='frontend_server.Tag'),
        ),
    ]
