# Generated by Django 2.2.12 on 2021-06-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0003_auto_20210529_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text_data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In work', 'In work'), ('Ready to deliver', 'Ready to deliver'), ('On the way', 'On the way'), ('Delivered', 'Deliverd')], max_length=50),
        ),
    ]
