# Generated by Django 2.2.12 on 2021-06-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0004_auto_20210604_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_data',
            field=models.TextField(null=True),
        ),
    ]
