# Generated by Django 2.2.12 on 2021-06-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0005_auto_20210604_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
    ]
