# Generated by Django 2.2.12 on 2021-06-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0006_auto_20210604_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
