# Generated by Django 2.2.12 on 2021-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0007_document_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='text_data',
            new_name='html_data',
        ),
        migrations.AddField(
            model_name='document',
            name='markdown_data',
            field=models.TextField(null=True),
        ),
    ]
