# Generated by Django 2.2.12 on 2021-06-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0008_auto_20210606_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('task', models.CharField(max_length=300, null=True)),
                ('deadline', models.DateField()),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief', to='frontend_server.Employee')),
                ('executors', models.ManyToManyField(related_name='executors', to='frontend_server.Employee')),
            ],
        ),
    ]
