# Generated by Django 2.2.12 on 2021-07-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0012_auto_20210627_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='connection_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Telegram', 'Telegram'), ('Whats App', 'Whats App')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend_server.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In work', 'In work'), ('Ready to deliver', 'Ready to deliver'), ('On the way', 'On the way'), ('Delivered', 'Deliverd')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('In work', 'In work'), ('Ready to deliver', 'Ready to deliver'), ('On the way', 'On the way'), ('Delivered', 'Deliverd')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_server.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_server.Item')),
            ],
        ),
    ]
