# Generated by Django 2.2.12 on 2021-07-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0014_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contacts',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
