# Generated by Django 2.2.12 on 2021-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0015_order_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('15', '15'), ('15.5', '15.5'), ('16', '16'), ('16.5', '16.5'), ('17', '17'), ('17.5', '17.5'), ('18', '18'), ('18.5', '18.5'), ('19', '19'), ('19.5', '19.5'), ('20', '20'), ('20.5', '20.5'), ('21', '21')], max_length=50, null=True),
        ),
    ]
