# Generated by Django 2.2.12 on 2021-07-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0020_auto_20210707_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='connection_type',
            field=models.CharField(choices=[('Phone', 'Телефон'), ('Telegram', 'Телеграм'), ('Whats App', 'Вотс ап')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend_server.Item'),
        ),
    ]
