# Generated by Django 2.2.12 on 2021-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0021_auto_20210708_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='connection_type',
            field=models.CharField(choices=[('Телефон', 'Phone'), ('Телеграм', 'Telegram'), ('Вотс ап', 'Whats App')], max_length=50, null=True),
        ),
    ]
