# Generated by Django 2.2.12 on 2021-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0022_auto_20210708_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='connection_type',
            field=models.CharField(choices=[('Phone', 'Телефон'), ('Telegram', 'Телеграм'), ('Whats App', 'Вотс ап'), ('Instagram', 'Инстаграм')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
