# Generated by Django 2.2.12 on 2021-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0028_auto_20210708_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(null=True, upload_to='img/stock_photo/'),
        ),
    ]
