# Generated by Django 2.2.12 on 2021-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0030_auto_20210708_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('Получен', 'Получен'), ('В работе', 'В работе'), ('Готовится к доставке', 'Готовится к доставке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Получен', 'Получен'), ('В работе', 'В работе'), ('Готовится к доставке', 'Готовится к доставке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен')], default='Получен', max_length=50, null=True),
        ),
    ]
