# Generated by Django 2.2.12 on 2021-05-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Works', 'Works'), ('Dismissed', 'Dismissed'), ('On holiday', 'On holiday')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Bracelet', 'Bracelet')], max_length=50)),
                ('price', models.FloatField()),
                ('stock_balance', models.FloatField()),
            ],
        ),
    ]
