# Generated by Django 2.2.12 on 2021-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0002_employee_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
