# Generated by Django 2.2.12 on 2021-05-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0006_auto_20210529_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
