# Generated by Django 2.2.12 on 2021-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0007_remove_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(),
        ),
    ]
