# Generated by Django 2.2.12 on 2021-05-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0010_auto_20210529_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
