# Generated by Django 2.2.12 on 2021-05-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0012_auto_20210529_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(),
        ),
    ]
