# Generated by Django 2.2.12 on 2021-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0013_auto_20210529_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('Founder', 'Founder')], max_length=50),
        ),
    ]
