# Generated by Django 2.2.12 on 2021-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_server', '0014_auto_20210529_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
    ]
