# Generated by Django 2.2.12 on 2021-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('owner', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('markdown_data', models.TextField(null=True)),
                ('html_data', models.TextField(null=True)),
                ('is_link_public', models.BooleanField(default=False)),
                ('is_indexed', models.BooleanField(default=False)),
            ],
        ),
    ]
