# Generated by Django 2.2.12 on 2021-08-31 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210819_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
