# Generated by Django 2.2.12 on 2021-07-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('owner', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('markdown_data', models.TextField(null=True)),
                ('html_data', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Deliveryman', 'Deliveryman'), ('CEO', 'CEO'), ('CTO', 'CTO'), ('Founder', 'Founder')], max_length=50)),
                ('status', models.CharField(choices=[('Works', 'Works'), ('Dismissed', 'Dismissed'), ('On holiday', 'On holiday')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock_balance', models.FloatField()),
                ('item_image', models.ImageField(null=True, upload_to='stock_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('task', models.TextField(null=True)),
                ('deadline', models.DateField()),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief', to='factory.Employee')),
                ('executors', models.ManyToManyField(related_name='executors', to='factory.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('connection_type', models.CharField(choices=[('Phone', 'Телефон'), ('Telegram', 'Телеграм'), ('Whats App', 'Вотс ап'), ('Instagram', 'Инстаграм')], max_length=50, null=True)),
                ('contacts', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(choices=[('15', '15'), ('15.5', '15.5'), ('16', '16'), ('16.5', '16.5'), ('17', '17'), ('17.5', '17.5'), ('18', '18'), ('18.5', '18.5'), ('19', '19'), ('19.5', '19.5'), ('20', '20'), ('20.5', '20.5'), ('21', '21')], max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Получен', 'Получен'), ('В работе', 'В работе'), ('Готовится к доставке', 'Готовится к доставке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен')], default='Получен', max_length=50, null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='factory.Tag'),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Получен', 'Получен'), ('В работе', 'В работе'), ('Готовится к доставке', 'Готовится к доставке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Item')),
            ],
        ),
    ]
